title: R Programming Works
description: Personal and school works using R language
logo: rlogo.jpg
description: <a href="https://wei-kiat-tan.github.io/weikiat98.github.io/">Return to My Profile Page</a>
theme: jekyll-theme-minimal
